config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'books#index'

  resources :books do
    resources :comments, only: :create
    member do
      get 'genre_page'
    end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_one :genre
  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy
  has_many :chapters, dependent: :destroy
  accepts_nested_attributes_for :chapters, reject_if: :all_blank, allow_destroy: true

  with_options presence: true do
    validates :title
    validates :select_genre_id, numericality: { other_than: 1, message: 'を選択して下さい' }
  end
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :book
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :text, presence: true
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '文学・評論' },
    { id: 3, name: 'ビジネス・経済' },
    { id: 4, name: '歴史・地理' },
    { id: 5, name: '政治・社会' },
    { id: 6, name: '芸能・エンターテイメント' },
    { id: 7, name: 'アート・建築・デザイン' },
    { id: 8, name: '人文・思想・宗教' },
    { id: 9, name: '暮らし・健康・料理' },
    { id: 10, name: 'サイエンス・テクノロジー' },
    { id: 11, name: '趣味・実用' },
    { id: 12, name: '教育・自己啓発' },
    { id: 13, name: 'スポーツ・アウトドア' },
    { id: 14, name: '音楽' },
    { id: 15, name: '旅行・紀行' },
    { id: 16, name: 'コミックス' },
    { id: 17, name: 'ライトノベル' }
  ]
  include ActiveHash::Associations
  has_many :users
  belongs_to :book
end

app/models/occupation.rb
class Occupation < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '公務員' },
    { id: 3, name: '経営者・役員' },
    { id: 4, name: '会社員' },
    { id: 5, name: '自営業' },
    { id: 6, name: '自由業' },
    { id: 7, name: '専業主婦' },
    { id: 8, name: '専業主夫' },
    { id: 9, name: 'パート・アルバイト' },
    { id: 10, name: '学生' },
    { id: 11, name: 'その他' }
  ]
  include ActiveHash::Associations
  has_many :users
end

app/models/prototype.rb
class Prototype < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  validates :title, presence:  true
  validates :catch_copy, presence:  true
  validates :concept, presence:  true
  validates :image, presence: true

  has_many :comments, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  extend ActiveHash::Associations::ActiveRecordExtensions

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :genre
  belongs_to :occupation

  validates :name,          presence: true
  validates :profile,       presence: true
  validates :occupation_id, numericality: { other_than: 1 }
  validates :genre_id,      numericality: { other_than: 1 }
  has_many :comments, dependent: :destroy
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile, :occupation_id, :genre_id])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :move_to_index, except: [:index, :show, :new, :create]

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
    @book.chapters.build
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @book = Book.find(params[:id])
    @comment = Comment.new
    @chapter = Chapter.where(book_id: params[:id])
    @comments = @book.comments.includes(:user)
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    if book.update(book_params)
      redirect_to book_path
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to root_path
  end

  def genre_page
    @books = Book.all
    @book = Book.find(params[:id])
  end

  private

  def book_params
    params.require(:book).permit(
      :title,
      :image,
      :select_genre_id,
      :note,
      :chapter_box,
      chapters_attributes: [:id, :item, :_destroy]
    ).merge(user_id: current_user.id)
  end

  def move_to_index
    book = Book.find(params[:id])
    redirect_to action: :index unless user_signed_in? && current_user.id == book.user.id
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to book_path(@comment.book)
    else
      @book = @comment.book
      @comments = @book.comments
      render 'books/show'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, book_id: params[:book_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<div class="card">
  <%= link_to  book_path(book.id) do %>
    <%= image_tag book.image, class:"card__img" %>
  <% end %>

  <div class="card__body">
    <%= link_to book.title, book_path(book.id), class: :card__title%>
    <p class="card__summary">
      <%= Genre.find(book.select_genre_id).name %>
    </p>
    <%= link_to book.user.name, user_path(book.user.id), class: :card__user %>
  </div>
</div>

app/views/books/_chapter_item_fields.html.erb
<tr class="nested-fields">
 <td><%= f.text_field :item, placeholder: "（例）一章" %></td>
 <td><%= link_to_remove_association '行削除', f %></td>
</tr>

app/views/books/_form.html.erb
<%= form_with model: @book, local: true do |f| %>
  <div class="field">
    <%= f.label :title, "本のタイトル" %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :image, "本の画像" %><br />
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :select_genre_id, "ジャンル" %><br />
    <%= f.collection_select(:select_genre_id, Genre.all, :id, :name, {}, {class:"genre-select"}) %>
  </div>

  <div class="form-group">
    <%= "目次" %><br />
      <table id='detail-association-insertion-point1'>
        <%= f.fields_for :chapters do |detail| %>
          <% render 'chapter_item_fields', f: detail %>
        <% end %> 
      </table>

     <%= link_to_add_association '行を追加', f, :chapters, partial: 'chapter_item_fields', class: :co_form_btn,
     data: {
      association_insertion_node: '#detail-association-insertion-point1',
      association_insertion_method: 'append' } 
      %>
  </div>



  <div class="check_box">
        <%= f.label :chapter_box, "check" %><br/>
        <%= f.radio_button :chapter_box, "未読" %> 
        <%= f.label :chapter_box, "未読", {value: "未読", style: "display: inline-block;"} %>
        <%= f.radio_button :chapter_box, "途中" %>
        <%= f.label :chapter_box, "途中", {value: "途中", style: "display: inline-block;"} %>
        <%= f.radio_button :chapter_box, "完読" %>
        <%= f.label :chapter_box, "完読", {value: "完読", style: "display: inline-block;"} %>
      </div>

  <div class="field">
    <%= f.label :note, "メモ" %><br />
    <%= f.text_area :note, class: :form__text_memo %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/books/_side_bar.html.erb
<h2 class="inner_title">ジャンル一覧</h2><br/>
<div class="select_genre_all">

<% if @books.find_by(select_genre_id: 2 ).present? %>
  <P><%= link_to "文学・評論", genre_page_book_path(@books.find_by(select_genre_id: 2 )), class: :select_genre %></P>
<% end %>

<% if @books.find_by(select_genre_id: 3 ).present? %>
  <p><%= link_to "ビジネス・経済", genre_page_book_path(@books.find_by(select_genre_id: 3 )), class: :select_genre %></p>
<% end %>

<% if @books.find_by(select_genre_id: 4 ).present? %>
  <p><%= link_to "歴史・地理", genre_page_book_path(@books.find_by(select_genre_id: 4 )), class: :select_genre %></p>
<% end %>

<% if @books.find_by(select_genre_id: 5 ).present? %>
  <p><%= link_to "政治・社会", genre_page_book_path(@books.find_by(select_genre_id: 5 )), class: :select_genre %></P>
<% end %>

<% if @books.find_by(select_genre_id: 6 ).present? %>
  <p><%= link_to "芸能・エンターテイメント", genre_page_book_path(@books.find_by(select_genre_id: 6 )), class: :select_genre %></p>
<% end %>

<% if @books.find_by(select_genre_id: 7 ).present? %>
  <p><%= link_to "アート・建築・デザイン", genre_page_book_path(@books.find_by(select_genre_id: 7 )), class: :select_genre %></p>
<% end %>

<% if @books.find_by(select_genre_id: 8 ).present? %>
  <p><%= link_to "人文・思想・宗教", genre_page_book_path(@books.find_by(select_genre_id: 8 )), class: :select_genre %></p>
<% end %>

<% if @books.find_by(select_genre_id: 9 ).present? %>
  <p><%= link_to "暮らし・健康・料理", genre_page_book_path(@books.find_by(select_genre_id: 9 )), class: :select_genre %></p>
<% end %>

<% if @books.find_by(select_genre_id: 10 ).present? %>
  <p><%= link_to "サイエンス・テクノロジー", genre_page_book_path(@books.find_by(select_genre_id: 10 )), class: :select_genre %></p>
<% end %>

<% if @books.find_by(select_genre_id: 11 ).present? %>
  <p><%= link_to "趣味・実用", genre_page_book_path(@books.find_by(select_genre_id: 11 )), class: :select_genre %></p>
<% end %>

<% if @books.find_by(select_genre_id: 12 ).present? %>
  <p><%= link_to "教育・自己啓発", genre_page_book_path(@books.find_by(select_genre_id: 12 )), class: :select_genre %></p>
<% end %>

<% if @books.find_by(select_genre_id: 13 ).present? %>
  <p><%= link_to "スポーツ・アウトドア", genre_page_book_path(@books.find_by(select_genre_id: 13 )), class: :select_genre %></p>
<% end %>

<% if @books.find_by(select_genre_id: 14 ).present? %>
  <p><%= link_to "音楽", genre_page_book_path(@books.find_by(select_genre_id: 14 )), class: :select_genre %></p>
<% end %>

<% if @books.find_by(select_genre_id: 15 ).present? %>
  <p><%= link_to "旅行・紀行", genre_page_book_path(@books.find_by(select_genre_id: 15 )), class: :select_genre %></p>
<% end %>

<% if @books.find_by(select_genre_id: 16 ).present? %>
  <p><%= link_to "コミックス", genre_page_book_path(@books.find_by(select_genre_id: 16 )), class: :select_genre %></p>
<% end %>

<% if @books.find_by(select_genre_id: 17 ).present? %>
  <p><%= link_to "ライトノベル", genre_page_book_path(@books.find_by(select_genre_id: 17 )), class: :select_genre %></p>
<% end %>

</div>

app/views/books/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">プロトタイプ編集</h2>
      <%# 部分テンプレートでフォームを表示する %>
      <%= render  "form" %>
    </div>
  </div>
</div>

app/views/books/genre_page.html.erb
<main class="main">
 <div class="wrapper">
    <% if user_signed_in? %>
      <div class="inner">

        <div class="greeting" >
        <%= "#{Genre.find(@book.select_genre_id).name}のページ" %>
        <%= link_to "#{current_user.name}さん", user_path(current_user.id), class: :greeting__link%>
      </div >
    <% end %>

    <div class="card__wrapper">
    <% @books.each do |book|%>
      <% if book.select_genre_id == @book.select_genre_id  %>
        <%= render partial: 'book', locals: { book: book } %>
      <% end %>
    <%end%>
    </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main class="main">
  <div class="title-contents">
    <h2 class='service-title'>
      読みたい時に読むのが本
      <% if user_signed_in? %>
      <div class="greeting" >
        <%= "こんにちは、" %>
        <%= link_to "#{current_user.name}さん", user_path(current_user.id), class: :greeting__link%>
      </div >
      <% end %>
    </h2>
  </div>
  
 <div class="wrapper">
    <% if user_signed_in? %>
      <div class="side-bar">
        <%= render "side_bar" %>
      </div>

      <div class="inner">
        <h2 class="inner_title" >
          <%= "書籍一覧" %>
        </h2 >
        <div class="card__wrapper">
         <%= render partial: 'book', collection: @books %>
        </div>
      </div>
    <% end %>
  </div>
  <% unless user_signed_in? %>
    <div class="bookburn_top">
      <div class="bookburn_content">
      自分の持っている本を管理しよう。<br/>
      全部読む必要はない<br/>
      読みたい時に読みたいとこを読む<br/>
      気になったところだけを読む<br/>
      飽きたら違う本に手を出す<br/>
      記録だけしておけばいい<br/>
      それがコンセプト
      </div>
    </div>
  <% end %>
</main>

app/views/books/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">本の追加</h2>
        <%# 部分テンプレートでフォームを表示する %>
        <%= render  "form" %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<main class="main">
  <div class="inner">
    <div class="book__wrapper">
      <p class="book__hedding">
        <%= @book.title %>
      </p>
      <%= link_to @book.user.name, user_path(@book.user.id), class: :book__user %>

      <% if user_signed_in? && current_user.id == @book.user.id %>
        <div class="book__manage">
          <%= link_to "編集する", edit_book_path(@book.id), class: :book__btn %>
          <%= link_to "削除する", book_path(@book.id), class: "book__btn", method: :delete %>
        </div>
      <% end %>

      <div class="book__images">
          <%= image_tag @book.image %>
      </div>

      <div class="book__body">
        <div class="book__detail">
          <p class="detail__title">ジャンル</p>
          <p class="detail__message">
            <%= Genre.find(@book.select_genre_id).name %>
          </p>
        </div>

        <div class="book__detail">
          <p class="detail__title">目次</p>
          
            <% @chapter.each do |chapter| %>
              <p class="detail__message">
                <%=  chapter.item %>
              </p>
            <% end %>
            <div class="button_tag">
              <%= radio_button_tag( "chapter_box", "radio1",[checked = true]) %>
              <%= label_tag("chapter_box",@book.chapter_box)%>
            </div>
          
          <p class="detail__title">メモ</p>
          <%=  simple_format(h(@book.note)) %>
        </div>
        
      </div>

      <div class="book__comments">
        <% if current_user %> 
          <%= form_with model: [@book, @comment] ,local: true do |f| %>
            <div class="field">
              <%= f.label :text, "コメント" %><br />
              <%= f.text_field :text %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :book__btn %>
            </div>
          <% end %>
        <% end %>
        <ul class="comments_lists">
          <%# 投稿に紐づくコメントを一覧する処理を記述する %>
            <li class="comments_list">
               <% if @comments %>
                  <% @comments.each do |comment| %>
                  <p>
                    <%= link_to comment.user.name, user_path(comment.user.id), class: :comment_user %>
                    <%= comment.text %>
                  </p>
                  <% end %>
               <% end %>
            </li>
          <%# // 投稿に紐づくコメントを一覧する処理を記述する %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>BookBurn</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%# <script src="javascript/new_form.js" defer></script> %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("book_burn.png", class: :logo), root_path %>
          </div>

          <% if user_signed_in? %>
            <div class="nav__right" >
              <%=  link_to "ログアウト", destroy_user_session_path, method: :delete,class: :nav__logout %>
              <%=  link_to "New Book", new_book_path, class: :nav__btn %>
            </div >
          <%  else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © BOOK BURN All rights reserved.<br/>
      presented by TOSHIKI KAWAMURA
      </p>
    </footer>
  </body>
</html>

app/views/prototypes/_form.html.erb
<%= form_with model: @prototype, local: true do |f| %>
  <div class="field">
    <%= f.label :title, "プロトタイプの名称" %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :catch_copy, "キャッチコピー" %><br />
    <%= f.text_area :catch_copy, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :concept, "コンセプト" %><br />
    <%= f.text_area :concept, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :image, "プロトタイプの画像" %><br />
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/prototypes/index.html.erb
<main class="main">
  <div class="inner">
    <%# ログインしているときは以下を表示する %>
    <% if user_signed_in? %>
      <div class="greeting" >
        <%= "こんにちは、" %>
        <%= link_to "#{current_user.name}さん", user_path(current_user.id), class: :greeting__link%>
      </div >
    <% end %>
    <%# // ログインしているときは上記を表示する %>
    <div class="card__wrapper">
      <%# 投稿機能実装後、部分テンプレートでプロトタイプ投稿一覧を表示する %>
      <%= render partial: 'prototype', collection: @prototypes %>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<div class="main">
 <div class="wrapper">
      <%# <div class="side-bar">
        <%= render partial: 'books/side_bar', action: :new %>
      <%# </div> %> 
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.name}さんの情報"%>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.name %></td>
          </tr>
          <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2"><%= @user.profile %></td>
          </tr>
          <tr>
            <th class="table__col1">職業</th>
            <td class="table__col2"><%= @user.occupation.name %></td>
          </tr>
          <tr>
            <th class="table__col1">好きなジャンル</th>
            <td class="table__col2"><%= @user.genre.name %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.name}さんの本"%>
      </h2>
      <div class="user__card">
        <%= render partial: 'books/book', collection: @user.books %>
      </div>
    </div>
  </div>
  </div>
</div>